# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
### solution 1.1

import numpy as np ## importing numpy library

## defining array using random numbers
arr = np.random.randint(1,21,size=(5,5)) 

print("Array: \n", arr)

## replace 3rd column with 1
arr[:,2] = 1
print("Modified array: \n",arr)

Array: 
 [[18  5  7  5 18]
 [10  8 16 13  6]
 [11 11 13 13  3]
 [ 8  4 20  1 18]
 [10  5  3 19  1]]
Modified array: 
 [[18  5  1  5 18]
 [10  8  1 13  6]
 [11 11  1 13  3]
 [ 8  4  1  1 18]
 [10  5  1 19  1]]


In [ ]:
### solution 1.2

## array of (4,4) shape
arr = np.arange(1,17).reshape(4,4)

print("Array: \n", arr)

## replacing diagonal element with 0
np.fill_diagonal(arr,0)
print("Modified array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified array: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
### solution 2.1

#array of shape(6,6)

arr = np.arange(1,37).reshape(6,6)

print("Array: \n", arr)

print("sub-array: \n", arr[2:5,1:4])

Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
sub-array: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [ ]:
### solution 2.2

#array of shape(5,5)
arr = np.random.randint(1,51,size=(5,5))
print("Array: \n", arr)


# border elements
elements = np.concatenate((arr[0,:], arr[-1,:], arr[:,0], arr[:,-1]))
print("Border elements: \n", elements)

Array: 
 [[34 11 23 39  4]
 [ 4 47 49 23 23]
 [20 28 42 12 42]
 [ 8  4 19 45 49]
 [43 28 49 23 49]]
Border elements: 
 [34 11 23 39  4 43 28 49 23 49 34  4 20  8 43  4 23 42 49 49]


In [23]:
### solution 3.1

#array 1 of shape(3,4)
arr1 = np.random.randint(1,16,size=(3,4))

#array 2 of shape(3,4)
arr2 = np.random.randint(1,26,size=(3,4))

#addition of arrays
print("Element-wise addition of arrays: \n", arr1+arr2 )

#substraction of arrays
print("Element-wise addition of arrays: \n", arr1-arr2 )

#multiplication of arrays
print("Element-wise addition of arrays: \n", arr1*arr2 )

#division of arrays
print("Element-wise addition of arrays: \n", arr1/arr2 )

Element-wise addition of arrays: 
 [[30 20 17 16]
 [36 25 30 36]
 [25 13 14 10]]
Element-wise addition of arrays: 
 [[  0 -18  -3 -12]
 [ -6   5 -10 -14]
 [ -7  -3   6   2]]
Element-wise addition of arrays: 
 [[225  19  70  28]
 [315 150 200 275]
 [144  40  40  24]]
Element-wise addition of arrays: 
 [[1.         0.05263158 0.7        0.14285714]
 [0.71428571 1.5        0.5        0.44      ]
 [0.5625     0.625      2.5        1.5       ]]


In [31]:
### solution 3.2

#array of shape(4,4)
arr = np.arange(1,17).reshape(4,4)
print("Array: \n", arr)

#row-wise sum
print("Row-wise sum: \n", np.sum(arr,axis=0))

# column-wise sum
print("Column wise sum: \n", np.sum(arr, axis=1))

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum: 
 [28 32 36 40]
Column wise sum: 
 [10 26 42 58]


In [32]:
### solution 4.1

#array with shape(5,5)
arr = np.random.randint(1,51,size=(5,5))
print("Array: \n", arr)

#mean of array
print(f"mean of array: {np.mean(arr)}")

#mean of array
print(f"median of array: {np.median(arr)}")

#mean of array
print(f"standard deviation of array: {np.std(arr)}")

#mean of array
print(f"variance of array: {np.var(arr)}")

Array: 
 [[25 18  5 23 31]
 [49 14 33 41 19]
 [24 14 42 21 13]
 [41 45 47 11 42]
 [ 9 43 49 20 13]]
mean of array: 27.68
median of array: 24.0
standard deviation of array: 13.976322835424202
variance of array: 195.3376


In [35]:
### solution 4.2

#array of size(3,3)
arr = np.random.randint(1,10,size=(3,3))
print("array \n", arr)

#normalized array
normalized_array = (arr - np.mean(arr))/np.std(arr)
print("Normalized array: \n", normalized_array)

array 
 [[6 1 2]
 [5 9 4]
 [3 6 8]]
Normalized array: 
 [[ 0.44194174 -1.54679608 -1.14904852]
 [ 0.04419417  1.63518443 -0.35355339]
 [-0.75130096  0.44194174  1.23743687]]


In [ ]:
### Solution 5.1

#array with shape(3,3)
arr = np.random.randint(1,11,size=(3,3))
print("array: \n", arr)

#1D array
arr1 = np.random.randint(1,11,size=(3,))
print("1D array: \n", arr1)

#add 1D array to each row of 2D array
result = arr + arr1
print("Brodcasting: \n", result)

array: 
 [[5 2 1]
 [9 6 2]
 [1 7 4]]
1D array: 
 [7 7 5]
Brodcasting: 
 [[12  9  6]
 [16 13  7]
 [ 8 14  9]]


In [41]:
### solution 5.2

#array of shape(4,4)
arr = np.random.randint(1,16,size=(4,4))
print("Array: \n", arr)

#array of shape(4,)
arr1= np.random.randint(1,16,size=(4,))
print("1D Array: \n", arr)

#subtracting 1D arrray from each column of 2D array
print("Result: \n", arr - arr1[:, np.newaxis])


Array: 
 [[15 10 10  4]
 [ 2  6 14  6]
 [ 6  3 10  5]
 [15 15 10 10]]
1D Array: 
 [[15 10 10  4]
 [ 2  6 14  6]
 [ 6  3 10  5]
 [15 15 10 10]]
Result: 
 [[13  8  8  2]
 [-5 -1  7 -1]
 [-2 -5  2 -3]
 [10 10  5  5]]


In [43]:
### solution 6.1

#array of shape(3,3)
arr = np.random.randint(1,46,size=(3,3))
print("Array: \n", arr)

#determinant of array
print("Deteminant of array: \n", np.linalg.det(arr))

#inverse of array
print("Deteminant of array: \n", np.linalg.inv(arr))

#eignevalues of array
print("Deteminant of array: \n", np.linalg.eigvals(arr))

Array: 
 [[ 1  3 20]
 [ 8 14  6]
 [19 45 14]]
Deteminant of array: 
 1811.9999999999975
Deteminant of array: 
 [[-0.04083885  0.47350993 -0.14459161]
 [ 0.00110375 -0.20198675  0.08498896]
 [ 0.05187638  0.00662252 -0.00551876]]
Deteminant of array: 
 [41.0405622+0.j         -6.0202811+2.81205573j -6.0202811-2.81205573j]


In [45]:
### solution 6.2

#array of shape(2,3)
arr1 = np.random.randint(1,11,size=(2,3))
print("Array with shape(2,3): \n", arr1)
arr2 = np.random.randint(1,11,size=(3,2))
print("Array with shape(3,2): \n", arr2)

#matrix multiplication
print("Matrix multiplication: \n", np.dot(arr1, arr2))


Array with shape(2,3): 
 [[3 4 5]
 [8 3 7]]
Array with shape(3,2): 
 [[ 5  3]
 [ 3  1]
 [10  5]]
Matrix multiplication: 
 [[ 77  38]
 [119  62]]


In [47]:
### solution 7.1

#array of shape(3,3)
arr = np.random.randint(1,9,size=(3,3))
print("Array: \n", arr)

#reshape array to (1,9)
print("Reshape array to shape (1,9): \n", arr.reshape(1,9))

#reshape array to (9,1)
print("Reshape array to shape (9,1): \n", arr.reshape(9,1))

Array: 
 [[2 1 2]
 [4 1 6]
 [1 8 8]]
Reshape array to shape (1,9): 
 [[2 1 2 4 1 6 1 8 8]]
Reshape array to shape (9,1): 
 [[2]
 [1]
 [2]
 [4]
 [1]
 [6]
 [1]
 [8]
 [8]]


In [48]:
### solution 7.2

#array with shape(5,5)
arr = np.random.randint(1,16,size=(5,5))
print("Array: \n", arr)

#Flattened array
flattened_arr = arr.flatten()
print("Flattened array: \n", flattened_arr)

#reshaped array
reshaped_arr = flattened_arr.reshape(5,5)
print("Reshaped array: \n", reshaped_arr)

Array: 
 [[14 14  4  3 15]
 [13 12 12  3  3]
 [ 1  2 14 12  1]
 [12  5  1  8 15]
 [ 9  8 14 11  3]]
Flattened array: 
 [14 14  4  3 15 13 12 12  3  3  1  2 14 12  1 12  5  1  8 15  9  8 14 11
  3]
Reshaped array: 
 [[14 14  4  3 15]
 [13 12 12  3  3]
 [ 1  2 14 12  1]
 [12  5  1  8 15]
 [ 9  8 14 11  3]]


In [53]:
### solution 8.1

#array with shape(5,5)
arr = np.random.randint(1,11,size=(5,5))
print("Array: \n", arr)

#fancy indexing to extract corner elements
corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print("Corner elements: \n", corners)

Array: 
 [[ 9  6  2  4  7]
 [ 4 10  6  7  7]
 [ 2 10  4  3  2]
 [ 1  9  8  1  1]
 [10  5  2  6  2]]
Corner elements: 
 [ 9  7 10  2]


In [55]:
### solution 8.2

#array of shape(4,4)
arr = np.random.randint(1,16,size=(4,4))
print("Array: \n", arr)

#set all elements greater than 10 to 10
arr[arr>10]=10
print("modified array: \n", arr)

Array: 
 [[10  8 13  4]
 [ 1  6  4  1]
 [15  8 12  9]
 [ 7  8  2 15]]
modified array: 
 [[10  8 10  4]
 [ 1  6  4  1]
 [10  8 10  9]
 [ 7  8  2 10]]


In [58]:
### solution 9.1

#structured array
dtype = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('A',22,66.5), ('B',23,45.7),('C',21,58.5)],dtype=dtype)
print("Array: \n", data)

#sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted data \n", sorted_data)

Array: 
 [('A', 22, 66.5) ('B', 23, 45.7) ('C', 21, 58.5)]
Sorted data 
 [('C', 21, 58.5) ('A', 22, 66.5) ('B', 23, 45.7)]


In [59]:
### solution 9.2

#structued array
dtype = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)], dtype=dtype)

print("Array: \n", data)

#compute the Euclidean distance between each pair
distances = np.sqrt((data['x'][:,np.newaxis] - data['x'])**2 + (data['y'][:,np.newaxis] - data['y'])**2)
print("Euclidean distance: \n", distances)

Array: 
 [(1, 2) (3, 4) (5, 6)]
Euclidean distance: 
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [63]:
### solution 10.1

arr = np.random.randint(1,21,size=(4,4))

masked_arr = np.ma.masked_greater(arr,10)

print("Array: \n", arr)

print("Masked array: \n", masked_arr)

print("Sum of unmasked elements: \n", masked_arr.sum())

Array: 
 [[ 2  5 17 14]
 [ 7 18 20  7]
 [ 6  1  1  3]
 [19 14  9 11]]
Masked array: 
 [[2 5 -- --]
 [7 -- -- 7]
 [6 1 1 3]
 [-- -- 9 --]]
Sum of unmasked elements: 
 41


In [65]:
### solution 10.2

arr = np.random.randint(1,51,size=(3,3))
masked_arr = np.ma.masked_array(arr, mask=np.eye(3,dtype=bool))

print("Arraay: \n", arr)
print("Masked array: \n", masked_arr)

mean_unmasked = masked_arr.mean()
masked_arr = masked_arr.filled(mean_unmasked)
print("Masked array after replacing with mean: \n", masked_arr)

Arraay: 
 [[11 15 41]
 [45 39 35]
 [17 44  2]]
Masked array: 
 [[-- 15 41]
 [45 -- 35]
 [17 44 --]]
Masked array after replacing with mean: 
 [[32 15 41]
 [45 32 35]
 [17 44 32]]
