In [20]:
### importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [21]:
### data

from sklearn.datasets import make_classification

## creating dataset

X,y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

In [22]:
### train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)
print("Size of X-train: \n", X_train.shape)
print("Size of X-test: \n", X_test.shape)
print("Size of y-train: \n", y_train.shape)
print("Size of y-test: \n", y_test.shape)

Size of X-train: 
 (750, 10)
Size of X-test: 
 (250, 10)
Size of y-train: 
 (750,)
Size of y-test: 
 (250,)


In [23]:
## model training

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [24]:
y_pred = model.predict(X_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0]


In [25]:
## probability of classes

model.predict_proba(X_test)

array([[7.80402833e-01, 2.19597167e-01],
       [3.33949444e-02, 9.66605056e-01],
       [6.54296825e-01, 3.45703175e-01],
       [7.74596952e-02, 9.22540305e-01],
       [9.74932212e-01, 2.50677881e-02],
       [4.02885463e-02, 9.59711454e-01],
       [9.77941181e-01, 2.20588194e-02],
       [9.53536485e-01, 4.64635153e-02],
       [7.96205025e-01, 2.03794975e-01],
       [6.82676128e-01, 3.17323872e-01],
       [9.11092679e-01, 8.89073209e-02],
       [2.49227688e-01, 7.50772312e-01],
       [5.20867594e-01, 4.79132406e-01],
       [2.11303097e-01, 7.88696903e-01],
       [7.85887817e-01, 2.14112183e-01],
       [9.43614105e-01, 5.63858947e-02],
       [2.64777377e-02, 9.73522262e-01],
       [3.45014892e-01, 6.54985108e-01],
       [3.19886760e-01, 6.80113240e-01],
       [2.00611174e-01, 7.99388826e-01],
       [4.95911186e-01, 5.04088814e-01],
       [9.62345871e-01, 3.76541287e-02],
       [1.92455811e-01, 8.07544189e-01],
       [7.86728233e-01, 2.13271767e-01],
       [8.671754

In [26]:
### performance metrics

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy score: \n", accuracy_score(y_test, y_pred))

print("confusion matrix: \n", confusion_matrix(y_test, y_pred))

print("Classification report: \n", classification_report(y_test, y_pred))

Accuracy score: 
 0.84
confusion matrix: 
 [[ 98  15]
 [ 25 112]]
Classification report: 
               precision    recall  f1-score   support

           0       0.80      0.87      0.83       113
           1       0.88      0.82      0.85       137

    accuracy                           0.84       250
   macro avg       0.84      0.84      0.84       250
weighted avg       0.84      0.84      0.84       250



In [27]:
### hyperparameter tuning

penalty = ['l1','l2','elasticnet']
c_vals = [100,10,1.0,0.1,0.01]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

params = dict(penalty=penalty, C=c_vals, solver=solver)

### GridSearchCV

from sklearn.model_selection import GridSearchCV

## Stratified K fold
from sklearn.model_selection import StratifiedKFold

#instance of stratifiedKfold
cv = StratifiedKFold()

## GridSearchCV params instance
grid = GridSearchCV(model, params, scoring='accuracy',cv=cv, n_jobs=-1)

## fitting of grid
grid.fit(X_train, y_train)

d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [28]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [29]:
grid.best_score_

np.float64(0.8773333333333333)

In [30]:
### performance metrics
y_pred = grid.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy score: \n", accuracy_score(y_test, y_pred))

print("confusion matrix: \n", confusion_matrix(y_test, y_pred))

print("Classification report: \n", classification_report(y_test, y_pred))

Accuracy score: 
 0.84
confusion matrix: 
 [[103  10]
 [ 30 107]]
Classification report: 
               precision    recall  f1-score   support

           0       0.77      0.91      0.84       113
           1       0.91      0.78      0.84       137

    accuracy                           0.84       250
   macro avg       0.84      0.85      0.84       250
weighted avg       0.85      0.84      0.84       250



In [31]:
### RandomizedSearchCV

from sklearn.model_selection import RandomizedSearchCV

rndsearchcv = RandomizedSearchCV(model, params, cv=5,scoring='accuracy')

rndsearchcv.fit(X_train, y_train)

d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\KNMaterial\my_python\venv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fi

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [32]:
rndsearchcv.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 0.1}

In [33]:
rndsearchcv.best_score_

np.float64(0.8719999999999999)

In [34]:
### performance metrics
y_pred = rndsearchcv.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy score: \n", accuracy_score(y_test, y_pred))

print("confusion matrix: \n", confusion_matrix(y_test, y_pred))

print("Classification report: \n", classification_report(y_test, y_pred))

Accuracy score: 
 0.848
confusion matrix: 
 [[101  12]
 [ 26 111]]
Classification report: 
               precision    recall  f1-score   support

           0       0.80      0.89      0.84       113
           1       0.90      0.81      0.85       137

    accuracy                           0.85       250
   macro avg       0.85      0.85      0.85       250
weighted avg       0.85      0.85      0.85       250

